/**
 * [PROVIDES]: Mobile 端 Lucide 统一导出与类型
 * [DEPENDS]: lucide-react-native
 * [POS]: Mobile 端 Lucide 唯一入口，保证图标一致性
 *
 * [PROTOCOL]: 本文件变更时，必须更新此 Header 及所属目录 AGENTS.md
 */

import type { LucideIcon } from 'lucide-react-native';

export type AppIcon = LucideIcon;

export {
  CircleAlert as AlertCircleIcon,
  TriangleAlert as AlertTriangleIcon,
  ArrowRight,
  ArrowUp as ArrowUpIcon,
  AtSign as AtSignIcon,
  Bold,
  Brain,
  Check,
  CircleCheck as CheckCircle,
  CircleCheck as CheckCircleIcon,
  Check as CheckIcon,
  CheckSquare,
  ChevronDown,
  ChevronDown as ChevronDownIcon,
  ChevronLeft as ChevronLeftIcon,
  ChevronRight,
  ChevronRight as ChevronRightIcon,
  ChevronUp,
  ChevronUp as ChevronUpIcon,
  Circle,
  Clock,
  Clock as ClockIcon,
  Cloud as CloudIcon,
  CloudOff as CloudOffIcon,
  Code,
  Crown as CrownIcon,
  FileCode as FileCodeIcon,
  File as FileIcon,
  FileText,
  FileText as FileTextIcon,
  Folder as FolderIcon,
  Globe as GlobeIcon,
  HardDrive as HardDriveIcon,
  Heading1,
  Heading2,
  Heading3,
  Home as HomeIcon,
  Image,
  Image as ImageIcon,
  Italic,
  Key as KeyIcon,
  List,
  ListOrdered,
  LoaderCircle as Loader2,
  Lock as LockIcon,
  LogIn as LogInIcon,
  LogOut as LogOutIcon,
  Mail as MailIcon,
  Mic as MicIcon,
  Monitor as MonitorIcon,
  Moon as MoonIcon,
  Ellipsis as MoreHorizontalIcon,
  Palette as PaletteIcon,
  Paperclip as PaperclipIcon,
  Plus as PlusIcon,
  Quote,
  Redo,
  RefreshCw as RefreshCwIcon,
  Search as SearchIcon,
  Settings as SettingsIcon,
  Sparkles as SparklesIcon,
  Square as SquareIcon,
  SquarePen as SquarePenIcon,
  Strikethrough,
  Sun as SunIcon,
  Table,
  Terminal,
  Trash2 as Trash2Icon,
  Underline,
  Undo,
  User as UserIcon,
  X,
  CircleX as XCircle,
  X as XIcon,
} from 'lucide-react-native';
