/**
 * [PROVIDES]: Mobile 端 Hugeicons 统一导出与类型
 * [DEPENDS]: @hugeicons/core-free-icons, @hugeicons/react-native
 * [POS]: 替换 lucide-react-native 的唯一入口，保证图标一致性
 *
 * [PROTOCOL]: 本文件变更时，必须更新此 Header 及所属目录 AGENTS.md
 */

import type { IconSvgElement } from '@hugeicons/react-native';

export type AppIcon = IconSvgElement;

export {
  AlertCircleIcon,
  AlertTriangle as AlertTriangleIcon,
  ArrowRight,
  ArrowUpIcon,
  AtSign as AtSignIcon,
  Bold,
  Brain,
  Check,
  CheckCircle,
  CheckCircle as CheckCircleIcon,
  Check as CheckIcon,
  CheckSquare,
  ChevronDown,
  ChevronDown as ChevronDownIcon,
  ChevronLeft as ChevronLeftIcon,
  ChevronRight,
  ChevronRight as ChevronRightIcon,
  ChevronUp,
  ChevronUp as ChevronUpIcon,
  Circle,
  Clock,
  ClockIcon,
  CloudIcon,
  CloudOff as CloudOffIcon,
  Code,
  CrownIcon,
  FileCode as FileCodeIcon,
  FileIcon,
  FileText,
  FileText as FileTextIcon,
  FolderIcon,
  GlobeIcon,
  HardDriveIcon,
  Heading1,
  Heading2,
  Heading3,
  HomeIcon,
  Image,
  ImageIcon,
  Italic,
  KeyIcon,
  List,
  ListOrdered,
  LoaderCircle as Loader2,
  LockIcon,
  LogIn as LogInIcon,
  LogOut as LogOutIcon,
  MailIcon,
  MicIcon,
  Monitor as MonitorIcon,
  MoonIcon,
  MoreHorizontalIcon,
  Palette as PaletteIcon,
  Paperclip as PaperclipIcon,
  Plus as PlusIcon,
  Quote,
  Redo,
  RefreshCw as RefreshCwIcon,
  Search as SearchIcon,
  Settings as SettingsIcon,
  SparklesIcon,
  SquareIcon,
  SquarePen as SquarePenIcon,
  Strikethrough,
  SunIcon,
  Table,
  Terminal,
  Trash2 as Trash2Icon,
  Underline,
  Undo,
  UserIcon,
  X,
  XCircle,
  X as XIcon,
} from '@hugeicons/core-free-icons';
