packages:
  - 'apps/*'
  - 'apps/*/server'
  - 'apps/*/www'
  - 'apps/*/mobile'
  - 'apps/*/pc'
  - 'apps/*/site-template'
  - 'apps/*/publish-worker'
  - 'apps/*/vectorize'
  - 'packages/*'
  - 'tooling/*'
