export const MEMOX_WORKSPACE_CONTENT_CONSUMER_ID =
  'memox-workspace-content-consumer';
export const MEMOX_WORKSPACE_CONTENT_BATCH_LIMIT = 20;
export const MEMOX_WORKSPACE_CONTENT_LEASE_MS = 60_000;
export const MEMOX_WORKSPACE_CONTENT_MAX_BATCHES = 10;
export const MEMOX_WORKSPACE_CONTENT_HTTP_REPLAY_BATCH_LIMIT = 10;
export const MEMOX_WORKSPACE_CONTENT_HTTP_REPLAY_MAX_BATCHES = 1;
export const MEMOX_WORKSPACE_CONTENT_REDRIVE_LIMIT = 100;
export const MEMOX_WORKSPACE_CONTENT_RECONCILE_BATCH_LIMIT = 100;
export const MEMOX_WORKSPACE_CONTENT_RECONCILE_COOLDOWN_MS = 15 * 60_000;
