export const MEMOX_WORKSPACE_CONTENT_CONSUMER_ID =
  'memox-workspace-content-consumer';
export const MEMOX_WORKSPACE_CONTENT_BATCH_LIMIT = 20;
export const MEMOX_WORKSPACE_CONTENT_LEASE_MS = 60_000;
export const MEMOX_WORKSPACE_CONTENT_MAX_BATCHES = 10;
export const MEMOX_WORKSPACE_CONTENT_REDRIVE_LIMIT = 100;
