
// This file is automatically generated

export const METADATA = {
  "name": "@aiget/agents",
  "version": "0.3.3",
  "versions": {
    "@aiget/agents": "0.3.3",
    "openai": "^6"
  }
};

export default METADATA;
