// This file is automatically generated

export const METADATA = {
  name: '@moryflow/agents-openai',
  version: '0.3.3',
  versions: {
    '@moryflow/agents-openai': '0.3.3',
    '@moryflow/agents-core': 'workspace:*',
    openai: '^6',
  },
};

export default METADATA;
