/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as SitemapPagesDotxmlRouteImport } from './routes/sitemap-pages[.]xml'
import { Route as SitemapBlogDotxmlRouteImport } from './routes/sitemap-blog[.]xml'
import { Route as RobotsDottxtRouteImport } from './routes/robots[.]txt'
import { Route as Char123LocaleChar125RouteRouteImport } from './routes/{-$locale}/route'
import { Route as Char123LocaleChar125IndexRouteImport } from './routes/{-$locale}/index'
import { Route as Char123LocaleChar125UseCasesRouteImport } from './routes/{-$locale}/use-cases'
import { Route as Char123LocaleChar125TermsRouteImport } from './routes/{-$locale}/terms'
import { Route as Char123LocaleChar125TelegramAiAgentRouteImport } from './routes/{-$locale}/telegram-ai-agent'
import { Route as Char123LocaleChar125SecondBrainAppRouteImport } from './routes/{-$locale}/second-brain-app'
import { Route as Char123LocaleChar125PrivacyRouteImport } from './routes/{-$locale}/privacy'
import { Route as Char123LocaleChar125PricingRouteImport } from './routes/{-$locale}/pricing'
import { Route as Char123LocaleChar125NotesToWebsiteRouteImport } from './routes/{-$locale}/notes-to-website'
import { Route as Char123LocaleChar125LocalFirstAiNotesRouteImport } from './routes/{-$locale}/local-first-ai-notes'
import { Route as Char123LocaleChar125LocalFirstAiAgentRouteImport } from './routes/{-$locale}/local-first-ai-agent'
import { Route as Char123LocaleChar125FeaturesRouteImport } from './routes/{-$locale}/features'
import { Route as Char123LocaleChar125DownloadRouteImport } from './routes/{-$locale}/download'
import { Route as Char123LocaleChar125DigitalGardenAppRouteImport } from './routes/{-$locale}/digital-garden-app'
import { Route as Char123LocaleChar125AiNoteTakingAppRouteImport } from './routes/{-$locale}/ai-note-taking-app'
import { Route as Char123LocaleChar125AgentWorkspaceRouteImport } from './routes/{-$locale}/agent-workspace'
import { Route as Char123LocaleChar125AboutRouteImport } from './routes/{-$locale}/about'
import { Route as Char123LocaleChar125CompareIndexRouteImport } from './routes/{-$locale}/compare/index'
import { Route as Char123LocaleChar125BlogIndexRouteImport } from './routes/{-$locale}/blog/index'
import { Route as Char123LocaleChar125CompareOpenclawRouteImport } from './routes/{-$locale}/compare/openclaw'
import { Route as Char123LocaleChar125CompareObsidianRouteImport } from './routes/{-$locale}/compare/obsidian'
import { Route as Char123LocaleChar125CompareNotionRouteImport } from './routes/{-$locale}/compare/notion'
import { Route as Char123LocaleChar125CompareManusRouteImport } from './routes/{-$locale}/compare/manus'
import { Route as Char123LocaleChar125CompareCoworkRouteImport } from './routes/{-$locale}/compare/cowork'
import { Route as Char123LocaleChar125BlogSlugRouteImport } from './routes/{-$locale}/blog/$slug'
import { Route as ApiV1LatestReleaseRouteImport } from './routes/api/v1/latest-release'
import { Route as ApiV1HealthRouteImport } from './routes/api/v1/health'
import { Route as ApiV1GithubStarsRouteImport } from './routes/api/v1/github-stars'

const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapPagesDotxmlRoute = SitemapPagesDotxmlRouteImport.update({
  id: '/sitemap-pages.xml',
  path: '/sitemap-pages.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapBlogDotxmlRoute = SitemapBlogDotxmlRouteImport.update({
  id: '/sitemap-blog.xml',
  path: '/sitemap-blog.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const RobotsDottxtRoute = RobotsDottxtRouteImport.update({
  id: '/robots.txt',
  path: '/robots.txt',
  getParentRoute: () => rootRouteImport,
} as any)
const Char123LocaleChar125RouteRoute =
  Char123LocaleChar125RouteRouteImport.update({
    id: '/{-$locale}',
    path: '/{-$locale}',
    getParentRoute: () => rootRouteImport,
  } as any)
const Char123LocaleChar125IndexRoute =
  Char123LocaleChar125IndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => Char123LocaleChar125RouteRoute,
  } as any)
const Char123LocaleChar125UseCasesRoute =
  Char123LocaleChar125UseCasesRouteImport.update({
    id: '/use-cases',
    path: '/use-cases',
    getParentRoute: () => Char123LocaleChar125RouteRoute,
  } as any)
const Char123LocaleChar125TermsRoute =
  Char123LocaleChar125TermsRouteImport.update({
    id: '/terms',
    path: '/terms',
    getParentRoute: () => Char123LocaleChar125RouteRoute,
  } as any)
const Char123LocaleChar125TelegramAiAgentRoute =
  Char123LocaleChar125TelegramAiAgentRouteImport.update({
    id: '/telegram-ai-agent',
    path: '/telegram-ai-agent',
    getParentRoute: () => Char123LocaleChar125RouteRoute,
  } as any)
const Char123LocaleChar125SecondBrainAppRoute =
  Char123LocaleChar125SecondBrainAppRouteImport.update({
    id: '/second-brain-app',
    path: '/second-brain-app',
    getParentRoute: () => Char123LocaleChar125RouteRoute,
  } as any)
const Char123LocaleChar125PrivacyRoute =
  Char123LocaleChar125PrivacyRouteImport.update({
    id: '/privacy',
    path: '/privacy',
    getParentRoute: () => Char123LocaleChar125RouteRoute,
  } as any)
const Char123LocaleChar125PricingRoute =
  Char123LocaleChar125PricingRouteImport.update({
    id: '/pricing',
    path: '/pricing',
    getParentRoute: () => Char123LocaleChar125RouteRoute,
  } as any)
const Char123LocaleChar125NotesToWebsiteRoute =
  Char123LocaleChar125NotesToWebsiteRouteImport.update({
    id: '/notes-to-website',
    path: '/notes-to-website',
    getParentRoute: () => Char123LocaleChar125RouteRoute,
  } as any)
const Char123LocaleChar125LocalFirstAiNotesRoute =
  Char123LocaleChar125LocalFirstAiNotesRouteImport.update({
    id: '/local-first-ai-notes',
    path: '/local-first-ai-notes',
    getParentRoute: () => Char123LocaleChar125RouteRoute,
  } as any)
const Char123LocaleChar125LocalFirstAiAgentRoute =
  Char123LocaleChar125LocalFirstAiAgentRouteImport.update({
    id: '/local-first-ai-agent',
    path: '/local-first-ai-agent',
    getParentRoute: () => Char123LocaleChar125RouteRoute,
  } as any)
const Char123LocaleChar125FeaturesRoute =
  Char123LocaleChar125FeaturesRouteImport.update({
    id: '/features',
    path: '/features',
    getParentRoute: () => Char123LocaleChar125RouteRoute,
  } as any)
const Char123LocaleChar125DownloadRoute =
  Char123LocaleChar125DownloadRouteImport.update({
    id: '/download',
    path: '/download',
    getParentRoute: () => Char123LocaleChar125RouteRoute,
  } as any)
const Char123LocaleChar125DigitalGardenAppRoute =
  Char123LocaleChar125DigitalGardenAppRouteImport.update({
    id: '/digital-garden-app',
    path: '/digital-garden-app',
    getParentRoute: () => Char123LocaleChar125RouteRoute,
  } as any)
const Char123LocaleChar125AiNoteTakingAppRoute =
  Char123LocaleChar125AiNoteTakingAppRouteImport.update({
    id: '/ai-note-taking-app',
    path: '/ai-note-taking-app',
    getParentRoute: () => Char123LocaleChar125RouteRoute,
  } as any)
const Char123LocaleChar125AgentWorkspaceRoute =
  Char123LocaleChar125AgentWorkspaceRouteImport.update({
    id: '/agent-workspace',
    path: '/agent-workspace',
    getParentRoute: () => Char123LocaleChar125RouteRoute,
  } as any)
const Char123LocaleChar125AboutRoute =
  Char123LocaleChar125AboutRouteImport.update({
    id: '/about',
    path: '/about',
    getParentRoute: () => Char123LocaleChar125RouteRoute,
  } as any)
const Char123LocaleChar125CompareIndexRoute =
  Char123LocaleChar125CompareIndexRouteImport.update({
    id: '/compare/',
    path: '/compare/',
    getParentRoute: () => Char123LocaleChar125RouteRoute,
  } as any)
const Char123LocaleChar125BlogIndexRoute =
  Char123LocaleChar125BlogIndexRouteImport.update({
    id: '/blog/',
    path: '/blog/',
    getParentRoute: () => Char123LocaleChar125RouteRoute,
  } as any)
const Char123LocaleChar125CompareOpenclawRoute =
  Char123LocaleChar125CompareOpenclawRouteImport.update({
    id: '/compare/openclaw',
    path: '/compare/openclaw',
    getParentRoute: () => Char123LocaleChar125RouteRoute,
  } as any)
const Char123LocaleChar125CompareObsidianRoute =
  Char123LocaleChar125CompareObsidianRouteImport.update({
    id: '/compare/obsidian',
    path: '/compare/obsidian',
    getParentRoute: () => Char123LocaleChar125RouteRoute,
  } as any)
const Char123LocaleChar125CompareNotionRoute =
  Char123LocaleChar125CompareNotionRouteImport.update({
    id: '/compare/notion',
    path: '/compare/notion',
    getParentRoute: () => Char123LocaleChar125RouteRoute,
  } as any)
const Char123LocaleChar125CompareManusRoute =
  Char123LocaleChar125CompareManusRouteImport.update({
    id: '/compare/manus',
    path: '/compare/manus',
    getParentRoute: () => Char123LocaleChar125RouteRoute,
  } as any)
const Char123LocaleChar125CompareCoworkRoute =
  Char123LocaleChar125CompareCoworkRouteImport.update({
    id: '/compare/cowork',
    path: '/compare/cowork',
    getParentRoute: () => Char123LocaleChar125RouteRoute,
  } as any)
const Char123LocaleChar125BlogSlugRoute =
  Char123LocaleChar125BlogSlugRouteImport.update({
    id: '/blog/$slug',
    path: '/blog/$slug',
    getParentRoute: () => Char123LocaleChar125RouteRoute,
  } as any)
const ApiV1LatestReleaseRoute = ApiV1LatestReleaseRouteImport.update({
  id: '/api/v1/latest-release',
  path: '/api/v1/latest-release',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiV1HealthRoute = ApiV1HealthRouteImport.update({
  id: '/api/v1/health',
  path: '/api/v1/health',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiV1GithubStarsRoute = ApiV1GithubStarsRouteImport.update({
  id: '/api/v1/github-stars',
  path: '/api/v1/github-stars',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/{-$locale}': typeof Char123LocaleChar125RouteRouteWithChildren
  '/robots.txt': typeof RobotsDottxtRoute
  '/sitemap-blog.xml': typeof SitemapBlogDotxmlRoute
  '/sitemap-pages.xml': typeof SitemapPagesDotxmlRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/{-$locale}/about': typeof Char123LocaleChar125AboutRoute
  '/{-$locale}/agent-workspace': typeof Char123LocaleChar125AgentWorkspaceRoute
  '/{-$locale}/ai-note-taking-app': typeof Char123LocaleChar125AiNoteTakingAppRoute
  '/{-$locale}/digital-garden-app': typeof Char123LocaleChar125DigitalGardenAppRoute
  '/{-$locale}/download': typeof Char123LocaleChar125DownloadRoute
  '/{-$locale}/features': typeof Char123LocaleChar125FeaturesRoute
  '/{-$locale}/local-first-ai-agent': typeof Char123LocaleChar125LocalFirstAiAgentRoute
  '/{-$locale}/local-first-ai-notes': typeof Char123LocaleChar125LocalFirstAiNotesRoute
  '/{-$locale}/notes-to-website': typeof Char123LocaleChar125NotesToWebsiteRoute
  '/{-$locale}/pricing': typeof Char123LocaleChar125PricingRoute
  '/{-$locale}/privacy': typeof Char123LocaleChar125PrivacyRoute
  '/{-$locale}/second-brain-app': typeof Char123LocaleChar125SecondBrainAppRoute
  '/{-$locale}/telegram-ai-agent': typeof Char123LocaleChar125TelegramAiAgentRoute
  '/{-$locale}/terms': typeof Char123LocaleChar125TermsRoute
  '/{-$locale}/use-cases': typeof Char123LocaleChar125UseCasesRoute
  '/{-$locale}/': typeof Char123LocaleChar125IndexRoute
  '/api/v1/github-stars': typeof ApiV1GithubStarsRoute
  '/api/v1/health': typeof ApiV1HealthRoute
  '/api/v1/latest-release': typeof ApiV1LatestReleaseRoute
  '/{-$locale}/blog/$slug': typeof Char123LocaleChar125BlogSlugRoute
  '/{-$locale}/compare/cowork': typeof Char123LocaleChar125CompareCoworkRoute
  '/{-$locale}/compare/manus': typeof Char123LocaleChar125CompareManusRoute
  '/{-$locale}/compare/notion': typeof Char123LocaleChar125CompareNotionRoute
  '/{-$locale}/compare/obsidian': typeof Char123LocaleChar125CompareObsidianRoute
  '/{-$locale}/compare/openclaw': typeof Char123LocaleChar125CompareOpenclawRoute
  '/{-$locale}/blog': typeof Char123LocaleChar125BlogIndexRoute
  '/{-$locale}/compare': typeof Char123LocaleChar125CompareIndexRoute
}
export interface FileRoutesByTo {
  '/robots.txt': typeof RobotsDottxtRoute
  '/sitemap-blog.xml': typeof SitemapBlogDotxmlRoute
  '/sitemap-pages.xml': typeof SitemapPagesDotxmlRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/{-$locale}/about': typeof Char123LocaleChar125AboutRoute
  '/{-$locale}/agent-workspace': typeof Char123LocaleChar125AgentWorkspaceRoute
  '/{-$locale}/ai-note-taking-app': typeof Char123LocaleChar125AiNoteTakingAppRoute
  '/{-$locale}/digital-garden-app': typeof Char123LocaleChar125DigitalGardenAppRoute
  '/{-$locale}/download': typeof Char123LocaleChar125DownloadRoute
  '/{-$locale}/features': typeof Char123LocaleChar125FeaturesRoute
  '/{-$locale}/local-first-ai-agent': typeof Char123LocaleChar125LocalFirstAiAgentRoute
  '/{-$locale}/local-first-ai-notes': typeof Char123LocaleChar125LocalFirstAiNotesRoute
  '/{-$locale}/notes-to-website': typeof Char123LocaleChar125NotesToWebsiteRoute
  '/{-$locale}/pricing': typeof Char123LocaleChar125PricingRoute
  '/{-$locale}/privacy': typeof Char123LocaleChar125PrivacyRoute
  '/{-$locale}/second-brain-app': typeof Char123LocaleChar125SecondBrainAppRoute
  '/{-$locale}/telegram-ai-agent': typeof Char123LocaleChar125TelegramAiAgentRoute
  '/{-$locale}/terms': typeof Char123LocaleChar125TermsRoute
  '/{-$locale}/use-cases': typeof Char123LocaleChar125UseCasesRoute
  '/{-$locale}': typeof Char123LocaleChar125IndexRoute
  '/api/v1/github-stars': typeof ApiV1GithubStarsRoute
  '/api/v1/health': typeof ApiV1HealthRoute
  '/api/v1/latest-release': typeof ApiV1LatestReleaseRoute
  '/{-$locale}/blog/$slug': typeof Char123LocaleChar125BlogSlugRoute
  '/{-$locale}/compare/cowork': typeof Char123LocaleChar125CompareCoworkRoute
  '/{-$locale}/compare/manus': typeof Char123LocaleChar125CompareManusRoute
  '/{-$locale}/compare/notion': typeof Char123LocaleChar125CompareNotionRoute
  '/{-$locale}/compare/obsidian': typeof Char123LocaleChar125CompareObsidianRoute
  '/{-$locale}/compare/openclaw': typeof Char123LocaleChar125CompareOpenclawRoute
  '/{-$locale}/blog': typeof Char123LocaleChar125BlogIndexRoute
  '/{-$locale}/compare': typeof Char123LocaleChar125CompareIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/{-$locale}': typeof Char123LocaleChar125RouteRouteWithChildren
  '/robots.txt': typeof RobotsDottxtRoute
  '/sitemap-blog.xml': typeof SitemapBlogDotxmlRoute
  '/sitemap-pages.xml': typeof SitemapPagesDotxmlRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/{-$locale}/about': typeof Char123LocaleChar125AboutRoute
  '/{-$locale}/agent-workspace': typeof Char123LocaleChar125AgentWorkspaceRoute
  '/{-$locale}/ai-note-taking-app': typeof Char123LocaleChar125AiNoteTakingAppRoute
  '/{-$locale}/digital-garden-app': typeof Char123LocaleChar125DigitalGardenAppRoute
  '/{-$locale}/download': typeof Char123LocaleChar125DownloadRoute
  '/{-$locale}/features': typeof Char123LocaleChar125FeaturesRoute
  '/{-$locale}/local-first-ai-agent': typeof Char123LocaleChar125LocalFirstAiAgentRoute
  '/{-$locale}/local-first-ai-notes': typeof Char123LocaleChar125LocalFirstAiNotesRoute
  '/{-$locale}/notes-to-website': typeof Char123LocaleChar125NotesToWebsiteRoute
  '/{-$locale}/pricing': typeof Char123LocaleChar125PricingRoute
  '/{-$locale}/privacy': typeof Char123LocaleChar125PrivacyRoute
  '/{-$locale}/second-brain-app': typeof Char123LocaleChar125SecondBrainAppRoute
  '/{-$locale}/telegram-ai-agent': typeof Char123LocaleChar125TelegramAiAgentRoute
  '/{-$locale}/terms': typeof Char123LocaleChar125TermsRoute
  '/{-$locale}/use-cases': typeof Char123LocaleChar125UseCasesRoute
  '/{-$locale}/': typeof Char123LocaleChar125IndexRoute
  '/api/v1/github-stars': typeof ApiV1GithubStarsRoute
  '/api/v1/health': typeof ApiV1HealthRoute
  '/api/v1/latest-release': typeof ApiV1LatestReleaseRoute
  '/{-$locale}/blog/$slug': typeof Char123LocaleChar125BlogSlugRoute
  '/{-$locale}/compare/cowork': typeof Char123LocaleChar125CompareCoworkRoute
  '/{-$locale}/compare/manus': typeof Char123LocaleChar125CompareManusRoute
  '/{-$locale}/compare/notion': typeof Char123LocaleChar125CompareNotionRoute
  '/{-$locale}/compare/obsidian': typeof Char123LocaleChar125CompareObsidianRoute
  '/{-$locale}/compare/openclaw': typeof Char123LocaleChar125CompareOpenclawRoute
  '/{-$locale}/blog/': typeof Char123LocaleChar125BlogIndexRoute
  '/{-$locale}/compare/': typeof Char123LocaleChar125CompareIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/{-$locale}'
    | '/robots.txt'
    | '/sitemap-blog.xml'
    | '/sitemap-pages.xml'
    | '/sitemap.xml'
    | '/{-$locale}/about'
    | '/{-$locale}/agent-workspace'
    | '/{-$locale}/ai-note-taking-app'
    | '/{-$locale}/digital-garden-app'
    | '/{-$locale}/download'
    | '/{-$locale}/features'
    | '/{-$locale}/local-first-ai-agent'
    | '/{-$locale}/local-first-ai-notes'
    | '/{-$locale}/notes-to-website'
    | '/{-$locale}/pricing'
    | '/{-$locale}/privacy'
    | '/{-$locale}/second-brain-app'
    | '/{-$locale}/telegram-ai-agent'
    | '/{-$locale}/terms'
    | '/{-$locale}/use-cases'
    | '/{-$locale}/'
    | '/api/v1/github-stars'
    | '/api/v1/health'
    | '/api/v1/latest-release'
    | '/{-$locale}/blog/$slug'
    | '/{-$locale}/compare/cowork'
    | '/{-$locale}/compare/manus'
    | '/{-$locale}/compare/notion'
    | '/{-$locale}/compare/obsidian'
    | '/{-$locale}/compare/openclaw'
    | '/{-$locale}/blog'
    | '/{-$locale}/compare'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/robots.txt'
    | '/sitemap-blog.xml'
    | '/sitemap-pages.xml'
    | '/sitemap.xml'
    | '/{-$locale}/about'
    | '/{-$locale}/agent-workspace'
    | '/{-$locale}/ai-note-taking-app'
    | '/{-$locale}/digital-garden-app'
    | '/{-$locale}/download'
    | '/{-$locale}/features'
    | '/{-$locale}/local-first-ai-agent'
    | '/{-$locale}/local-first-ai-notes'
    | '/{-$locale}/notes-to-website'
    | '/{-$locale}/pricing'
    | '/{-$locale}/privacy'
    | '/{-$locale}/second-brain-app'
    | '/{-$locale}/telegram-ai-agent'
    | '/{-$locale}/terms'
    | '/{-$locale}/use-cases'
    | '/{-$locale}'
    | '/api/v1/github-stars'
    | '/api/v1/health'
    | '/api/v1/latest-release'
    | '/{-$locale}/blog/$slug'
    | '/{-$locale}/compare/cowork'
    | '/{-$locale}/compare/manus'
    | '/{-$locale}/compare/notion'
    | '/{-$locale}/compare/obsidian'
    | '/{-$locale}/compare/openclaw'
    | '/{-$locale}/blog'
    | '/{-$locale}/compare'
  id:
    | '__root__'
    | '/{-$locale}'
    | '/robots.txt'
    | '/sitemap-blog.xml'
    | '/sitemap-pages.xml'
    | '/sitemap.xml'
    | '/{-$locale}/about'
    | '/{-$locale}/agent-workspace'
    | '/{-$locale}/ai-note-taking-app'
    | '/{-$locale}/digital-garden-app'
    | '/{-$locale}/download'
    | '/{-$locale}/features'
    | '/{-$locale}/local-first-ai-agent'
    | '/{-$locale}/local-first-ai-notes'
    | '/{-$locale}/notes-to-website'
    | '/{-$locale}/pricing'
    | '/{-$locale}/privacy'
    | '/{-$locale}/second-brain-app'
    | '/{-$locale}/telegram-ai-agent'
    | '/{-$locale}/terms'
    | '/{-$locale}/use-cases'
    | '/{-$locale}/'
    | '/api/v1/github-stars'
    | '/api/v1/health'
    | '/api/v1/latest-release'
    | '/{-$locale}/blog/$slug'
    | '/{-$locale}/compare/cowork'
    | '/{-$locale}/compare/manus'
    | '/{-$locale}/compare/notion'
    | '/{-$locale}/compare/obsidian'
    | '/{-$locale}/compare/openclaw'
    | '/{-$locale}/blog/'
    | '/{-$locale}/compare/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  Char123LocaleChar125RouteRoute: typeof Char123LocaleChar125RouteRouteWithChildren
  RobotsDottxtRoute: typeof RobotsDottxtRoute
  SitemapBlogDotxmlRoute: typeof SitemapBlogDotxmlRoute
  SitemapPagesDotxmlRoute: typeof SitemapPagesDotxmlRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  ApiV1GithubStarsRoute: typeof ApiV1GithubStarsRoute
  ApiV1HealthRoute: typeof ApiV1HealthRoute
  ApiV1LatestReleaseRoute: typeof ApiV1LatestReleaseRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap-pages.xml': {
      id: '/sitemap-pages.xml'
      path: '/sitemap-pages.xml'
      fullPath: '/sitemap-pages.xml'
      preLoaderRoute: typeof SitemapPagesDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap-blog.xml': {
      id: '/sitemap-blog.xml'
      path: '/sitemap-blog.xml'
      fullPath: '/sitemap-blog.xml'
      preLoaderRoute: typeof SitemapBlogDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/robots.txt': {
      id: '/robots.txt'
      path: '/robots.txt'
      fullPath: '/robots.txt'
      preLoaderRoute: typeof RobotsDottxtRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/{-$locale}': {
      id: '/{-$locale}'
      path: '/{-$locale}'
      fullPath: '/{-$locale}'
      preLoaderRoute: typeof Char123LocaleChar125RouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/{-$locale}/': {
      id: '/{-$locale}/'
      path: '/'
      fullPath: '/{-$locale}/'
      preLoaderRoute: typeof Char123LocaleChar125IndexRouteImport
      parentRoute: typeof Char123LocaleChar125RouteRoute
    }
    '/{-$locale}/use-cases': {
      id: '/{-$locale}/use-cases'
      path: '/use-cases'
      fullPath: '/{-$locale}/use-cases'
      preLoaderRoute: typeof Char123LocaleChar125UseCasesRouteImport
      parentRoute: typeof Char123LocaleChar125RouteRoute
    }
    '/{-$locale}/terms': {
      id: '/{-$locale}/terms'
      path: '/terms'
      fullPath: '/{-$locale}/terms'
      preLoaderRoute: typeof Char123LocaleChar125TermsRouteImport
      parentRoute: typeof Char123LocaleChar125RouteRoute
    }
    '/{-$locale}/telegram-ai-agent': {
      id: '/{-$locale}/telegram-ai-agent'
      path: '/telegram-ai-agent'
      fullPath: '/{-$locale}/telegram-ai-agent'
      preLoaderRoute: typeof Char123LocaleChar125TelegramAiAgentRouteImport
      parentRoute: typeof Char123LocaleChar125RouteRoute
    }
    '/{-$locale}/second-brain-app': {
      id: '/{-$locale}/second-brain-app'
      path: '/second-brain-app'
      fullPath: '/{-$locale}/second-brain-app'
      preLoaderRoute: typeof Char123LocaleChar125SecondBrainAppRouteImport
      parentRoute: typeof Char123LocaleChar125RouteRoute
    }
    '/{-$locale}/privacy': {
      id: '/{-$locale}/privacy'
      path: '/privacy'
      fullPath: '/{-$locale}/privacy'
      preLoaderRoute: typeof Char123LocaleChar125PrivacyRouteImport
      parentRoute: typeof Char123LocaleChar125RouteRoute
    }
    '/{-$locale}/pricing': {
      id: '/{-$locale}/pricing'
      path: '/pricing'
      fullPath: '/{-$locale}/pricing'
      preLoaderRoute: typeof Char123LocaleChar125PricingRouteImport
      parentRoute: typeof Char123LocaleChar125RouteRoute
    }
    '/{-$locale}/notes-to-website': {
      id: '/{-$locale}/notes-to-website'
      path: '/notes-to-website'
      fullPath: '/{-$locale}/notes-to-website'
      preLoaderRoute: typeof Char123LocaleChar125NotesToWebsiteRouteImport
      parentRoute: typeof Char123LocaleChar125RouteRoute
    }
    '/{-$locale}/local-first-ai-notes': {
      id: '/{-$locale}/local-first-ai-notes'
      path: '/local-first-ai-notes'
      fullPath: '/{-$locale}/local-first-ai-notes'
      preLoaderRoute: typeof Char123LocaleChar125LocalFirstAiNotesRouteImport
      parentRoute: typeof Char123LocaleChar125RouteRoute
    }
    '/{-$locale}/local-first-ai-agent': {
      id: '/{-$locale}/local-first-ai-agent'
      path: '/local-first-ai-agent'
      fullPath: '/{-$locale}/local-first-ai-agent'
      preLoaderRoute: typeof Char123LocaleChar125LocalFirstAiAgentRouteImport
      parentRoute: typeof Char123LocaleChar125RouteRoute
    }
    '/{-$locale}/features': {
      id: '/{-$locale}/features'
      path: '/features'
      fullPath: '/{-$locale}/features'
      preLoaderRoute: typeof Char123LocaleChar125FeaturesRouteImport
      parentRoute: typeof Char123LocaleChar125RouteRoute
    }
    '/{-$locale}/download': {
      id: '/{-$locale}/download'
      path: '/download'
      fullPath: '/{-$locale}/download'
      preLoaderRoute: typeof Char123LocaleChar125DownloadRouteImport
      parentRoute: typeof Char123LocaleChar125RouteRoute
    }
    '/{-$locale}/digital-garden-app': {
      id: '/{-$locale}/digital-garden-app'
      path: '/digital-garden-app'
      fullPath: '/{-$locale}/digital-garden-app'
      preLoaderRoute: typeof Char123LocaleChar125DigitalGardenAppRouteImport
      parentRoute: typeof Char123LocaleChar125RouteRoute
    }
    '/{-$locale}/ai-note-taking-app': {
      id: '/{-$locale}/ai-note-taking-app'
      path: '/ai-note-taking-app'
      fullPath: '/{-$locale}/ai-note-taking-app'
      preLoaderRoute: typeof Char123LocaleChar125AiNoteTakingAppRouteImport
      parentRoute: typeof Char123LocaleChar125RouteRoute
    }
    '/{-$locale}/agent-workspace': {
      id: '/{-$locale}/agent-workspace'
      path: '/agent-workspace'
      fullPath: '/{-$locale}/agent-workspace'
      preLoaderRoute: typeof Char123LocaleChar125AgentWorkspaceRouteImport
      parentRoute: typeof Char123LocaleChar125RouteRoute
    }
    '/{-$locale}/about': {
      id: '/{-$locale}/about'
      path: '/about'
      fullPath: '/{-$locale}/about'
      preLoaderRoute: typeof Char123LocaleChar125AboutRouteImport
      parentRoute: typeof Char123LocaleChar125RouteRoute
    }
    '/{-$locale}/compare/': {
      id: '/{-$locale}/compare/'
      path: '/compare'
      fullPath: '/{-$locale}/compare'
      preLoaderRoute: typeof Char123LocaleChar125CompareIndexRouteImport
      parentRoute: typeof Char123LocaleChar125RouteRoute
    }
    '/{-$locale}/blog/': {
      id: '/{-$locale}/blog/'
      path: '/blog'
      fullPath: '/{-$locale}/blog'
      preLoaderRoute: typeof Char123LocaleChar125BlogIndexRouteImport
      parentRoute: typeof Char123LocaleChar125RouteRoute
    }
    '/{-$locale}/compare/openclaw': {
      id: '/{-$locale}/compare/openclaw'
      path: '/compare/openclaw'
      fullPath: '/{-$locale}/compare/openclaw'
      preLoaderRoute: typeof Char123LocaleChar125CompareOpenclawRouteImport
      parentRoute: typeof Char123LocaleChar125RouteRoute
    }
    '/{-$locale}/compare/obsidian': {
      id: '/{-$locale}/compare/obsidian'
      path: '/compare/obsidian'
      fullPath: '/{-$locale}/compare/obsidian'
      preLoaderRoute: typeof Char123LocaleChar125CompareObsidianRouteImport
      parentRoute: typeof Char123LocaleChar125RouteRoute
    }
    '/{-$locale}/compare/notion': {
      id: '/{-$locale}/compare/notion'
      path: '/compare/notion'
      fullPath: '/{-$locale}/compare/notion'
      preLoaderRoute: typeof Char123LocaleChar125CompareNotionRouteImport
      parentRoute: typeof Char123LocaleChar125RouteRoute
    }
    '/{-$locale}/compare/manus': {
      id: '/{-$locale}/compare/manus'
      path: '/compare/manus'
      fullPath: '/{-$locale}/compare/manus'
      preLoaderRoute: typeof Char123LocaleChar125CompareManusRouteImport
      parentRoute: typeof Char123LocaleChar125RouteRoute
    }
    '/{-$locale}/compare/cowork': {
      id: '/{-$locale}/compare/cowork'
      path: '/compare/cowork'
      fullPath: '/{-$locale}/compare/cowork'
      preLoaderRoute: typeof Char123LocaleChar125CompareCoworkRouteImport
      parentRoute: typeof Char123LocaleChar125RouteRoute
    }
    '/{-$locale}/blog/$slug': {
      id: '/{-$locale}/blog/$slug'
      path: '/blog/$slug'
      fullPath: '/{-$locale}/blog/$slug'
      preLoaderRoute: typeof Char123LocaleChar125BlogSlugRouteImport
      parentRoute: typeof Char123LocaleChar125RouteRoute
    }
    '/api/v1/latest-release': {
      id: '/api/v1/latest-release'
      path: '/api/v1/latest-release'
      fullPath: '/api/v1/latest-release'
      preLoaderRoute: typeof ApiV1LatestReleaseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/v1/health': {
      id: '/api/v1/health'
      path: '/api/v1/health'
      fullPath: '/api/v1/health'
      preLoaderRoute: typeof ApiV1HealthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/v1/github-stars': {
      id: '/api/v1/github-stars'
      path: '/api/v1/github-stars'
      fullPath: '/api/v1/github-stars'
      preLoaderRoute: typeof ApiV1GithubStarsRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface Char123LocaleChar125RouteRouteChildren {
  Char123LocaleChar125AboutRoute: typeof Char123LocaleChar125AboutRoute
  Char123LocaleChar125AgentWorkspaceRoute: typeof Char123LocaleChar125AgentWorkspaceRoute
  Char123LocaleChar125AiNoteTakingAppRoute: typeof Char123LocaleChar125AiNoteTakingAppRoute
  Char123LocaleChar125DigitalGardenAppRoute: typeof Char123LocaleChar125DigitalGardenAppRoute
  Char123LocaleChar125DownloadRoute: typeof Char123LocaleChar125DownloadRoute
  Char123LocaleChar125FeaturesRoute: typeof Char123LocaleChar125FeaturesRoute
  Char123LocaleChar125LocalFirstAiAgentRoute: typeof Char123LocaleChar125LocalFirstAiAgentRoute
  Char123LocaleChar125LocalFirstAiNotesRoute: typeof Char123LocaleChar125LocalFirstAiNotesRoute
  Char123LocaleChar125NotesToWebsiteRoute: typeof Char123LocaleChar125NotesToWebsiteRoute
  Char123LocaleChar125PricingRoute: typeof Char123LocaleChar125PricingRoute
  Char123LocaleChar125PrivacyRoute: typeof Char123LocaleChar125PrivacyRoute
  Char123LocaleChar125SecondBrainAppRoute: typeof Char123LocaleChar125SecondBrainAppRoute
  Char123LocaleChar125TelegramAiAgentRoute: typeof Char123LocaleChar125TelegramAiAgentRoute
  Char123LocaleChar125TermsRoute: typeof Char123LocaleChar125TermsRoute
  Char123LocaleChar125UseCasesRoute: typeof Char123LocaleChar125UseCasesRoute
  Char123LocaleChar125IndexRoute: typeof Char123LocaleChar125IndexRoute
  Char123LocaleChar125BlogSlugRoute: typeof Char123LocaleChar125BlogSlugRoute
  Char123LocaleChar125CompareCoworkRoute: typeof Char123LocaleChar125CompareCoworkRoute
  Char123LocaleChar125CompareManusRoute: typeof Char123LocaleChar125CompareManusRoute
  Char123LocaleChar125CompareNotionRoute: typeof Char123LocaleChar125CompareNotionRoute
  Char123LocaleChar125CompareObsidianRoute: typeof Char123LocaleChar125CompareObsidianRoute
  Char123LocaleChar125CompareOpenclawRoute: typeof Char123LocaleChar125CompareOpenclawRoute
  Char123LocaleChar125BlogIndexRoute: typeof Char123LocaleChar125BlogIndexRoute
  Char123LocaleChar125CompareIndexRoute: typeof Char123LocaleChar125CompareIndexRoute
}

const Char123LocaleChar125RouteRouteChildren: Char123LocaleChar125RouteRouteChildren =
  {
    Char123LocaleChar125AboutRoute: Char123LocaleChar125AboutRoute,
    Char123LocaleChar125AgentWorkspaceRoute:
      Char123LocaleChar125AgentWorkspaceRoute,
    Char123LocaleChar125AiNoteTakingAppRoute:
      Char123LocaleChar125AiNoteTakingAppRoute,
    Char123LocaleChar125DigitalGardenAppRoute:
      Char123LocaleChar125DigitalGardenAppRoute,
    Char123LocaleChar125DownloadRoute: Char123LocaleChar125DownloadRoute,
    Char123LocaleChar125FeaturesRoute: Char123LocaleChar125FeaturesRoute,
    Char123LocaleChar125LocalFirstAiAgentRoute:
      Char123LocaleChar125LocalFirstAiAgentRoute,
    Char123LocaleChar125LocalFirstAiNotesRoute:
      Char123LocaleChar125LocalFirstAiNotesRoute,
    Char123LocaleChar125NotesToWebsiteRoute:
      Char123LocaleChar125NotesToWebsiteRoute,
    Char123LocaleChar125PricingRoute: Char123LocaleChar125PricingRoute,
    Char123LocaleChar125PrivacyRoute: Char123LocaleChar125PrivacyRoute,
    Char123LocaleChar125SecondBrainAppRoute:
      Char123LocaleChar125SecondBrainAppRoute,
    Char123LocaleChar125TelegramAiAgentRoute:
      Char123LocaleChar125TelegramAiAgentRoute,
    Char123LocaleChar125TermsRoute: Char123LocaleChar125TermsRoute,
    Char123LocaleChar125UseCasesRoute: Char123LocaleChar125UseCasesRoute,
    Char123LocaleChar125IndexRoute: Char123LocaleChar125IndexRoute,
    Char123LocaleChar125BlogSlugRoute: Char123LocaleChar125BlogSlugRoute,
    Char123LocaleChar125CompareCoworkRoute:
      Char123LocaleChar125CompareCoworkRoute,
    Char123LocaleChar125CompareManusRoute:
      Char123LocaleChar125CompareManusRoute,
    Char123LocaleChar125CompareNotionRoute:
      Char123LocaleChar125CompareNotionRoute,
    Char123LocaleChar125CompareObsidianRoute:
      Char123LocaleChar125CompareObsidianRoute,
    Char123LocaleChar125CompareOpenclawRoute:
      Char123LocaleChar125CompareOpenclawRoute,
    Char123LocaleChar125BlogIndexRoute: Char123LocaleChar125BlogIndexRoute,
    Char123LocaleChar125CompareIndexRoute:
      Char123LocaleChar125CompareIndexRoute,
  }

const Char123LocaleChar125RouteRouteWithChildren =
  Char123LocaleChar125RouteRoute._addFileChildren(
    Char123LocaleChar125RouteRouteChildren,
  )

const rootRouteChildren: RootRouteChildren = {
  Char123LocaleChar125RouteRoute: Char123LocaleChar125RouteRouteWithChildren,
  RobotsDottxtRoute: RobotsDottxtRoute,
  SitemapBlogDotxmlRoute: SitemapBlogDotxmlRoute,
  SitemapPagesDotxmlRoute: SitemapPagesDotxmlRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  ApiV1GithubStarsRoute: ApiV1GithubStarsRoute,
  ApiV1HealthRoute: ApiV1HealthRoute,
  ApiV1LatestReleaseRoute: ApiV1LatestReleaseRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
