
// This file is automatically generated

export const METADATA = {
  "name": "@moryflow/agents-core",
  "version": "0.3.3",
  "versions": {
    "@moryflow/agents-core": "0.3.3",
    "openai": "^6"
  }
};

export default METADATA;
