
// This file is automatically generated

export const METADATA = {
  "name": "@moryflow/agents",
  "version": "0.3.3",
  "versions": {
    "@moryflow/agents": "0.3.3",
    "@moryflow/agents-core": "workspace:*",
    "@moryflow/agents-openai": "workspace:*",
    "@moryflow/agents-realtime": "workspace:*",
    "openai": "^6"
  }
};

export default METADATA;
