/**
 * [PROVIDES]: 生成构建期 metadata（用于 agents 包的版本信息注入；只注入稳定字段）
 * [DEPENDS]: package.json 依赖、node:fs/node:path/node:process
 * [POS]: packages/agents* 的 prebuild 脚本入口
 *
 * [PROTOCOL]: 本文件变更时，必须更新此 Header 及所属目录 CLAUDE.md
 */

const { readFileSync, writeFileSync } = require('node:fs');
const { resolve } = require('node:path');
const { cwd } = require('node:process');

const packageJson = JSON.parse(
  readFileSync(resolve(cwd(), 'package.json'), 'utf-8'),
);

const METADATA = {
  name: packageJson.name,
  version: packageJson.version,
};

const output = `
// This file is automatically generated

export const METADATA = ${JSON.stringify(METADATA, null, 2)};

export default METADATA;
`;

writeFileSync(resolve(cwd(), 'src/metadata.ts'), output, 'utf-8');
