
// This file is automatically generated

export const METADATA = {
  "name": "@aiget/agents-realtime",
  "version": "0.3.3",
  "versions": {
    "@aiget/agents-realtime": "0.3.3"
  }
};

export default METADATA;
