/**
 * Screenshots 页面 - 截图历史
 */
import { useState } from 'react'
import {
  Badge,
  Card,
  CardContent,
  Skeleton,
  Empty,
  Button,
} from '@aiget/ui/primitives'
import { PageHeader, SimplePagination } from '@aiget/ui/composed'
import { formatRelativeTime } from '@aiget/ui/lib'
import { ExternalLink, Image, RefreshCw } from 'lucide-react'
import {
  useScreenshots,
  type Screenshot,
  SCREENSHOT_STATUS_CONFIG,
  ScreenshotDetailDialog,
} from '@/features/screenshots'

const PAGE_SIZE = 12

/** 安全地提取 URL hostname */
function getHostname(url: string): string {
  try {
    return new URL(url).hostname
  } catch {
    return url
  }
}

export default function ScreenshotsPage() {
  const [page, setPage] = useState(1)
  const [selectedScreenshot, setSelectedScreenshot] = useState<Screenshot | null>(null)

  const { data, isLoading, refetch, isRefetching } = useScreenshots({
    page,
    limit: PAGE_SIZE,
  })

  const screenshots = data?.data ?? []
  const totalPages = data ? Math.ceil(data.total / PAGE_SIZE) : 0

  return (
    <div className="space-y-6">
      <PageHeader
        title="Screenshots"
        description="View all screenshots generated by API calls"
        action={
          <Button
            variant="outline"
            size="sm"
            onClick={() => refetch()}
            disabled={isRefetching}
          >
            <RefreshCw className={`mr-2 h-4 w-4 ${isRefetching ? 'animate-spin' : ''}`} />
            Refresh
          </Button>
        }
      />

      {isLoading ? (
        <div className="grid gap-4 sm:grid-cols-2 lg:grid-cols-3">
          {Array.from({ length: 6 }).map((_, i) => (
            <Card key={i}>
              <Skeleton className="aspect-video w-full" />
              <CardContent className="p-4">
                <Skeleton className="mb-2 h-4 w-3/4" />
                <Skeleton className="h-3 w-1/2" />
              </CardContent>
            </Card>
          ))}
        </div>
      ) : screenshots.length === 0 ? (
        <Card>
          <Empty className="py-12">
            <Image className="mb-4 h-12 w-12 text-muted-foreground" />
            <p className="text-muted-foreground">No screenshots yet</p>
            <p className="mt-1 text-sm text-muted-foreground">
              Screenshots generated via API will appear here
            </p>
          </Empty>
        </Card>
      ) : (
        <>
          <div className="grid gap-4 sm:grid-cols-2 lg:grid-cols-3">
            {screenshots.map((screenshot) => {
              const statusConfig = SCREENSHOT_STATUS_CONFIG[screenshot.status] ?? {
                label: screenshot.status,
                variant: 'outline' as const,
              }

              return (
                <Card
                  key={screenshot.id}
                  className="cursor-pointer overflow-hidden transition-shadow hover:shadow-md"
                  onClick={() => setSelectedScreenshot(screenshot)}
                >
                  {/* 预览图 */}
                  <div className="relative aspect-video bg-muted">
                    {screenshot.fileUrl && screenshot.status === 'COMPLETED' ? (
                      <img
                        src={screenshot.fileUrl}
                        alt={screenshot.pageTitle || screenshot.url}
                        className="h-full w-full object-cover"
                        loading="lazy"
                      />
                    ) : screenshot.status === 'PROCESSING' || screenshot.status === 'PENDING' ? (
                      <div className="flex h-full items-center justify-center">
                        <RefreshCw className="h-6 w-6 animate-spin text-muted-foreground" />
                      </div>
                    ) : (
                      <div className="flex h-full items-center justify-center">
                        <span className="text-sm text-muted-foreground">Screenshot failed</span>
                      </div>
                    )}
                    {/* 状态标签 */}
                    <Badge
                      variant={statusConfig.variant}
                      className="absolute right-2 top-2"
                    >
                      {statusConfig.label}
                    </Badge>
                    {/* 缓存标识 */}
                    {screenshot.fromCache && (
                      <Badge variant="secondary" className="absolute left-2 top-2">
                        Cached
                      </Badge>
                    )}
                  </div>

                  {/* 信息 */}
                  <CardContent className="p-4">
                    <div className="mb-2 flex items-center gap-1 text-sm">
                      <span className="truncate" title={screenshot.url}>
                        {screenshot.pageTitle || getHostname(screenshot.url)}
                      </span>
                      <a
                        href={screenshot.url}
                        target="_blank"
                        rel="noopener noreferrer"
                        className="shrink-0 text-muted-foreground hover:text-foreground"
                        onClick={(e) => e.stopPropagation()}
                      >
                        <ExternalLink className="h-3 w-3" />
                      </a>
                    </div>
                    <div className="flex items-center justify-between text-xs text-muted-foreground">
                      <span>{formatRelativeTime(screenshot.createdAt)}</span>
                      {screenshot.processingMs && (
                        <span>{screenshot.processingMs}ms</span>
                      )}
                    </div>
                  </CardContent>
                </Card>
              )
            })}
          </div>

          {/* 分页 */}
          {totalPages > 1 && (
            <div className="flex justify-center">
              <SimplePagination
                page={page}
                totalPages={totalPages}
                onPageChange={setPage}
              />
            </div>
          )}
        </>
      )}

      {/* 详情对话框 */}
      <ScreenshotDetailDialog
        screenshot={selectedScreenshot}
        open={!!selectedScreenshot}
        onOpenChange={(open) => !open && setSelectedScreenshot(null)}
      />
    </div>
  )
}
