
// This file is automatically generated

export const METADATA = {
  "name": "@moryflow/agents-realtime",
  "version": "0.3.3",
  "versions": {
    "@moryflow/agents-realtime": "0.3.3",
    "@moryflow/agents-core": "workspace:*"
  }
};

export default METADATA;
